[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn composeexample.wsgi --log-file -"
healthcheckPath = "/inicio/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
